### ISSUE TITLE
PRIMARY keyword

### ISSUE THREAD

**Issue by zouharvi** [zouharvi/ZimaDB#25]
See `test/scripts/create_table.sh`

Primary keys throw an error in `CREATE TABLE ..` context.

**Comment by zouharvi** [comment]
`PRIMARY KEY` syntax appears functional. See `src/share/models/queries/create_table.cpp`

```
            if (primary_key != -1)
            {
                specific_err(ok, "Error: Multiple PRIMARY KEYS");
                break;
            }
```

**Comment by OpenGround** [comment]
Seems as if it's working correctly?
I currently don't see any problems.

**Comment by zouharvi** [comment]
With -O3
```
zimadb> create table rostlinka (a int PRIMARY KEY, b int PRIMARY KEY);
a : INT PRIMARY KEY ASC
Error: Multiple PRIMARY KEYS
```

**Comment by zouharvi** [comment]
I see. :slightly_smiling_face:
